{application,ollama,
             [{config_mtime,1734195384},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,jason,nimble_options,
                             plug,req]},
              {description,"A nifty little library for working with Ollama in Elixir."},
              {modules,['Elixir.Ollama','Elixir.Ollama.Blob',
                        'Elixir.Ollama.HTTPError','Elixir.Ollama.Schemas']},
              {registered,[]},
              {vsn,"0.7.1"}]}.
